name: jd15-discovery

services:
  app:
    build: .
    container_name: jd15-discovery
    ports:
      - "8761:8761"
    networks:
      - discovery-net

networks:
  discovery-net:
    name: discovery-net
    driver: bridge